services:
  api:
    build: .
    volumes:
    - ./alembic/versions:/app/alembic/versions
    ports:
      - "8070:8070"
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_started
      redis:
        condition: service_started
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:S3crtKfiJ4@db:5432/postgres
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
    command: sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8070"

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=S3crtKfiJ4
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672" # for Celery
      - "15672:15672" # for web-interface
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  celery_worker:
    build: .
    command: celery -A celery_main worker --loglevel=info
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_started
      redis:
        condition: service_started
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:S3crtKfiJ4@db:5432/postgres
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
    volumes:
      - .:/app
    
volumes:
  postgres_data: